name: Branch validating

on: push

jobs:
  run-validation:
    name: Validate Branch name
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+' # Regex the branch should match. This example enforces grouping
          ignore: main # Ignore exactly matching branch names from convention

